// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnrFdThWeae6pkRRWPUGAcW6IeauSa3uM',
    appId: '1:638036168244:web:bb742e6e8aa1e518a88461',
    messagingSenderId: '638036168244',
    projectId: 'schedule-university',
    authDomain: 'schedule-university.firebaseapp.com',
    storageBucket: 'schedule-university.firebasestorage.app',
    measurementId: 'G-MCV1KMCBXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgT0Yech2XgNuX9Bh-sOjTE3wQ8I2af18',
    appId: '1:638036168244:android:1a9ec3947464ce47a88461',
    messagingSenderId: '638036168244',
    projectId: 'schedule-university',
    storageBucket: 'schedule-university.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCflm9EIDvXaOK2Ub3lQq_naklAQ4oLibA',
    appId: '1:638036168244:ios:ad3334119e22e777a88461',
    messagingSenderId: '638036168244',
    projectId: 'schedule-university',
    storageBucket: 'schedule-university.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCflm9EIDvXaOK2Ub3lQq_naklAQ4oLibA',
    appId: '1:638036168244:ios:ad3334119e22e777a88461',
    messagingSenderId: '638036168244',
    projectId: 'schedule-university',
    storageBucket: 'schedule-university.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnrFdThWeae6pkRRWPUGAcW6IeauSa3uM',
    appId: '1:638036168244:web:58485472a26352a8a88461',
    messagingSenderId: '638036168244',
    projectId: 'schedule-university',
    authDomain: 'schedule-university.firebaseapp.com',
    storageBucket: 'schedule-university.firebasestorage.app',
    measurementId: 'G-NKR4HZEVY9',
  );
}
